ecosys_add_cocco fails with CESM1850ECO_ECOCESM20
If the compset doesn't set OCN_BGC_CONFIG to latest, cesm2.1, or anything
containing "cocco" then shell_commands will exit with an error status.

diff --git a/cime_config/testdefs/testmods_dirs/pop/ecosys_add_cocco/shell_commands b/cime_config/testdefs/testmods_dirs/pop/ecosys_add_cocco/shell_commands
--- a/cime_config/testdefs/testmods_dirs/pop/ecosys_add_cocco/shell_commands
+++ b/cime_config/testdefs/testmods_dirs/pop/ecosys_add_cocco/shell_commands
@@ -5,4 +5,7 @@ if [[ "${ocn_bgc_config}" == "latest" ]]; then
   ./xmlchange OCN_BGC_CONFIG=with_cocco
 elif [[ "${ocn_bgc_config}" == "cesm2.1" ]]; then
   ./xmlchange OCN_BGC_CONFIG=cesm2.1+cocco
+elif [[ "${ocn_bgc_config}" != *"cocco"* ]]; then
+  echo "ERROR: OCN_BGC_CONFIG=${ocn_bgc_config} does not have equivalent option with coccolithophores"
+  exit 1
 fi
